#!/usr/bin/env python3
"""Generate Pydantic models from JSON Schema.

This script uses datamodel-code-generator to create Pydantic v2 models
from the report.schema.json file.

Usage:
    python scripts/generate_models.py           # Generate models
    python scripts/generate_models.py --check   # Check if models are up-to-date (CI)
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

# Paths
ROOT = Path(__file__).parent.parent
SCHEMA_PATH = ROOT / "schema" / "report.schema.json"
OUTPUT_PATH = ROOT / "src" / "pytest_aitest" / "models" / "_generated.py"

# datamodel-codegen arguments
CODEGEN_ARGS = [
    sys.executable, "-m", "datamodel_code_generator",
    "--input", str(SCHEMA_PATH),
    "--output", str(OUTPUT_PATH),
    "--output-model-type", "pydantic_v2.BaseModel",
    "--target-python-version", "3.11",
    "--use-double-quotes",
    "--use-standard-collections",
    "--use-union-operator",
    "--collapse-root-models",
    "--field-constraints",
    "--use-field-description",
    "--capitalise-enum-members",
    "--enum-field-as-literal", "one",
    "--use-default-kwarg",
    "--strict-nullable",
]

HEADER = '''"""Auto-generated Pydantic models from schema/report.schema.json.

DO NOT EDIT THIS FILE DIRECTLY.
Run `python scripts/generate_models.py` to regenerate.
"""

'''


def generate_models() -> str:
    """Generate models and return the content."""
    # Ensure output directory exists
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    
    # Run datamodel-codegen
    result = subprocess.run(
        CODEGEN_ARGS,
        capture_output=True,
        text=True,
    )
    
    if result.returncode != 0:
        print(f"Error generating models:\n{result.stderr}", file=sys.stderr)
        sys.exit(1)
    
    # Read generated content and add header
    content = OUTPUT_PATH.read_text()
    
    # Add our header after the first docstring/imports if present
    # or just prepend if no docstring
    if content.startswith('"""') or content.startswith("'''"):
        # Find end of docstring
        end_quote = '"""' if content.startswith('"""') else "'''"
        end_idx = content.find(end_quote, 3) + 3
        content = HEADER + content[end_idx:].lstrip()
    elif content.startswith("# generated"):
        # Skip any auto-generated comments
        lines = content.split("\n")
        skip = 0
        for i, line in enumerate(lines):
            if line.startswith("#") or not line.strip():
                skip = i + 1
            else:
                break
        content = HEADER + "\n".join(lines[skip:])
    else:
        content = HEADER + content
    
    # Write back with header
    OUTPUT_PATH.write_text(content)
    
    return content


def check_models() -> bool:
    """Check if generated models are up-to-date."""
    if not OUTPUT_PATH.exists():
        print(f"Generated models not found: {OUTPUT_PATH}")
        return False
    
    # Read current content
    current_content = OUTPUT_PATH.read_text()
    
    # Generate new content to temp location
    import tempfile
    with tempfile.NamedTemporaryFile(mode="w", suffix=".py", delete=False) as f:
        temp_path = Path(f.name)
    
    # Temporarily change output path
    temp_args = CODEGEN_ARGS.copy()
    temp_args[temp_args.index("--output") + 1] = str(temp_path)
    
    result = subprocess.run(temp_args, capture_output=True, text=True)
    if result.returncode != 0:
        print(f"Error generating models:\n{result.stderr}", file=sys.stderr)
        temp_path.unlink(missing_ok=True)
        return False
    
    # Read and add header
    new_content = temp_path.read_text()
    if new_content.startswith('"""') or new_content.startswith("'''"):
        end_quote = '"""' if new_content.startswith('"""') else "'''"
        end_idx = new_content.find(end_quote, 3) + 3
        new_content = HEADER + new_content[end_idx:].lstrip()
    elif new_content.startswith("# generated"):
        lines = new_content.split("\n")
        skip = 0
        for i, line in enumerate(lines):
            if line.startswith("#") or not line.strip():
                skip = i + 1
            else:
                break
        new_content = HEADER + "\n".join(lines[skip:])
    else:
        new_content = HEADER + new_content
    
    temp_path.unlink()
    
    # Compare
    if current_content.strip() != new_content.strip():
        print("Generated models are out of date!")
        print("Run `python scripts/generate_models.py` to update.")
        return False
    
    print("Generated models are up-to-date.")
    return True


def main() -> None:
    if "--check" in sys.argv:
        if not check_models():
            sys.exit(1)
    else:
        print(f"Generating models from {SCHEMA_PATH}...")
        generate_models()
        print(f"Generated: {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
